import Container from "@/UI/layout/Container";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import data from "@/data";
import SocialLink from "@/components/SocialLink/SocialLink";
import {
  Behance,
  EnvelopeFill,
  Facebook,
  Instagram,
  Twitter,
  Youtube,
} from "react-bootstrap-icons";

const { contact } = data;
const { image, socialLinks, email } = contact;
function Contact() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-between flex-col min-h-screen">
        <Navbar active={4} />
        <Container>
          <div className="flex gap-[80px] items-center w-full">
            <Image
              src={image}
              alt="profile image"
              width={380}
              height={380}
              className="bg-contain rounded-[16px] rotate-[3deg] h-[380px] w-[380px]"
            />
            <div className="flex flex-col justify-between h-full gap-6">
              <SocialLink
                Icon={Facebook}
                link={socialLinks.facebook}
                name={"Facebook"}
              />
              <SocialLink
                Icon={Instagram}
                link={socialLinks.instagram}
                name={"Instagram"}
              />
              <SocialLink
                Icon={Twitter}
                link={socialLinks.twitter}
                name={"Twitter"}
              />
              <SocialLink
                Icon={Behance}
                link={socialLinks.behance}
                name={"Behance"}
              />
              <SocialLink
                Icon={Youtube}
                link={socialLinks.youtube}
                name={"Youtube"}
              />
            </div>
          </div>
          <div className="flex w-full items-center justify-center">
            <span className="flex items-center justify-center gap-3 mt-4">
              <EnvelopeFill className="text-2xl text-gray-500 dark:text-gray-400" />{" "}
              <p className="text-gray-700 dark:text-gray-300 text-xl">
                {email}
              </p>
            </span>
          </div>
        </Container>
        <Footer />
      </main>
    </>
  );
}

export default Contact;
